### ISSUE TITLE
Support for nginx

### ISSUE THREAD

**Issue by maxstoyanov** [phpManufaktur/kitFramework#4]
At the moment the kitFramework only supports apache servers but ngnix is also often used, but needs to be configured differently.

**Comment by hertsch** [comment]
That's no longer correct! Since kitFramework 0.20 support also nginx and works nice i.e. at XAMPP under windows ... 8-)

**Comment by maxstoyanov** [comment]
Sorry, I meant rewrite rules and all the settings made in the htacces for apache.

**Comment by hertsch** [comment]
This is well documented and should be no problem [Webserver Configuration](http://silex.sensiolabs.org/doc/web_servers.html). We can add a link to the Wiki.
